---
title: "plotly examples"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

# Data exploration using NYC restaurant inspection data from the Department of Health and Mental Hygiene

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```


```{r}

brooklyn_food =
rest_inspec %>%
  drop_na() %>%
  select(boro, dba, zipcode, critical_flag, cuisine_description, score, grade, grade_date, violation_code, violation_description)%>%
  filter(boro == "BROOKLYN") %>%
  mutate(
    zipcode = as.factor(zipcode),
    grade = as.factor(grade)
  )

  
#head(brooklyn_food)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Distribution of scores by Brooklyn zipcodes


```{r}
#boxplots, brooklyn zipcodes and distribution of scores
brooklyn_food %>%
  mutate(zipcode = fct_reorder(zipcode, score)) %>% 
  plot_ly(x = ~zipcode, y = ~score, color = ~zipcode, type = "box", colors = "viridis") %>%
  layout(
    xaxis = list(title = "Brooklyn zipcodes")
  )

```


Column {data-width=350}
-----------------------------------------------------------------------

### Grade counts in Brooklyn

```{r}
#grade counts in Brooklyn

brooklyn_food %>%
  count(grade) %>% 
  mutate(grade = fct_reorder(grade, n)) %>% 
  plot_ly(x = ~grade, y = ~n, color = ~grade, type = "bar", colors = "plasma")

```

### Grade counts by date in Brooklyn

```{r}


brooklyn_food %>%
count(grade, grade_date) %>%
  group_by(grade, grade_date) %>%
  plot_ly (
    x = ~grade_date, y = ~n, color = ~grade, type = "scatter", mode = "markers", colors = "viridis",
    alpha = .5
  )

```